### ISSUE TITLE
bmdplay 1080p25 problem

### ISSUE THREAD

**Issue by sbelet** [lu-zero/bmdtools#89]
Hi,

In our test we find out that when we use/set output video mode as 1080p25, **bmdplay** outputs 1080i50. And this cause problem.
You can be sure that all settings are correctly set and double (or even triple) checked.
The output checked by industry professional devices. This is how we know and sure it's 1080i50.

A fix will be appreciated. Thanks for advance.

**Comment by lu-zero** [comment]
could you please check if the testcase in the drivers works as intended?

On Jun 21, 2017 21:04, "kamilz" <notifications@github.com> wrote:

Hi,

In our test we find out that when we use/set output video mode as 1080p25,
*bmdplay* outputs 1080i50. And this cause problem.
You can be sure that all settings are correctly set and double (or even
triple) checked.
The output checked by industry professional devices. This is how we know
and sure it's 1080i50.

A fix will be appreciated. Thanks for advance.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/lu-zero/bmdtools/issues/89>, or mute the thread

**Comment by sbelet** [comment]
Hi,

Yes we tested _testpattern_ executable in SDK, also works same, issue remains.
We believe this problem related to PsF vs progressive setting.

We do some research on this too. I'm closing the ticket/issue.
Anyway, thanks for help.
